# NLLB-200 / FLORES-200 Language Registry
# Maps script-specific code keys (ISO 639-3 + ISO 15924 script) to human-readable names.

LANGUAGES = [
    {"code": "auto", "name": "Auto Detect Language"},
    {"code": "eng_Latn", "name": "English (Latin)"},
    {"code": "hin_Deva", "name": "Hindi (Devanagari)"},
    {"code": "spa_Latn", "name": "Spanish (Latin)"},
    {"code": "fra_Latn", "name": "French (Latin)"},
    {"code": "deu_Latn", "name": "German (Latin)"},
    {"code": "ita_Latn", "name": "Italian (Latin)"},
    {"code": "jpn_Jpan", "name": "Japanese"},
    {"code": "zho_Hans", "name": "Chinese (Simplified)"},
    {"code": "zho_Hant", "name": "Chinese (Traditional)"},
    {"code": "rus_Cyrl", "name": "Russian (Cyrillic)"},
    {"code": "ara_Arab", "name": "Arabic"},
    {"code": "por_Latn", "name": "Portuguese (Latin)"},
    {"code": "urd_Arab", "name": "Urdu (Arabic)"},
    {"code": "ben_Beng", "name": "Bengali"},
    {"code": "pan_Guru", "name": "Punjabi (Gurmukhi)"},
    {"code": "mar_Deva", "name": "Marathi (Devanagari)"},
    {"code": "tam_Taml", "name": "Tamil"},
    {"code": "tel_Telu", "name": "Telugu"},
    {"code": "guj_Gujr", "name": "Gujarati"},
    {"code": "kan_Knda", "name": "Kannada"},
    {"code": "mal_Mlym", "name": "Malayalam"},
    {"code": "asm_Beng", "name": "Assamese"},
    {"code": "bho_Deva", "name": "Bhojpuri"},
    {"code": "san_Deva", "name": "Sanskrit (Devanagari)"},
    {"code": "nep_Deva", "name": "Nepali (Devanagari)"},
    {"code": "kor_Kore", "name": "Korean"},
    {"code": "vie_Latn", "name": "Vietnamese (Latin)"},
    {"code": "tha_Thai", "name": "Thai"},
    {"code": "ind_Latn", "name": "Indonesian (Latin)"},
    {"code": "tur_Latn", "name": "Turkish (Latin)"},
    {"code": "nld_Latn", "name": "Dutch (Latin)"},
    {"code": "pol_Latn", "name": "Polish (Latin)"},
    {"code": "swe_Latn", "name": "Swedish (Latin)"},
    {"code": "dan_Latn", "name": "Danish (Latin)"},
    {"code": "nob_Latn", "name": "Norwegian Bokmål (Latin)"},
    {"code": "fin_Latn", "name": "Finnish (Latin)"},
    {"code": "ces_Latn", "name": "Czech (Latin)"},
    {"code": "slk_Latn", "name": "Slovak (Latin)"},
    {"code": "hun_Latn", "name": "Hungarian (Latin)"},
    {"code": "ron_Latn", "name": "Romanian (Latin)"},
    {"code": "bul_Cyrl", "name": "Bulgarian (Cyrillic)"},
    {"code": "ukr_Cyrl", "name": "Ukrainian (Cyrillic)"},
    {"code": "ell_Grek", "name": "Greek (Greek)"},
    {"code": "heb_Hebr", "name": "Hebrew"},
    {"code": "pes_Arab", "name": "Persian (Arabic)"},
    {"code": "tgk_Cyrl", "name": "Tajik (Cyrillic)"},
    {"code": "kaz_Cyrl", "name": "Kazakh (Cyrillic)"},
    {"code": "kir_Cyrl", "name": "Kyrgyz (Cyrillic)"},
    {"code": "uzn_Latn", "name": "Uzbek (Latin)"},
    {"code": "tgl_Latn", "name": "Tagalog (Latin)"},
    {"code": "msa_Latn", "name": "Malay (Latin)"},
    {"code": "khm_Khmr", "name": "Khmer (Khmer)"},
    {"code": "lao_Laoo", "name": "Lao"},
    {"code": "mya_Mymr", "name": "Burmese"},
    {"code": "sun_Latn", "name": "Sundanese (Latin)"},
    {"code": "jav_Latn", "name": "Javanese (Latin)"},
    {"code": "swh_Latn", "name": "Swahili (Latin)"},
    {"code": "yor_Latn", "name": "Yoruba (Latin)"},
    {"code": "ibo_Latn", "name": "Igbo (Latin)"},
    {"code": "zul_Latn", "name": "Zulu (Latin)"},
    {"code": "xho_Latn", "name": "Xhosa (Latin)"},
    {"code": "afr_Latn", "name": "Afrikaans (Latin)"},
    {"code": "amh_Ethi", "name": "Amharic (Ethiopic)"},
    {"code": "som_Latn", "name": "Somali (Latin)"},
    {"code": "tir_Ethi", "name": "Tigrinya (Ethiopic)"},
    {"code": "mlt_Latn", "name": "Maltese (Latin)"},
    {"code": "isl_Latn", "name": "Icelandic (Latin)"},
    {"code": "gle_Latn", "name": "Irish (Latin)"},
    {"code": "cym_Latn", "name": "Welsh (Latin)"},
    {"code": "cat_Latn", "name": "Catalan (Latin)"},
    {"code": "glg_Latn", "name": "Galician (Latin)"},
    {"code": "eus_Latn", "name": "Basque (Latin)"},
    {"code": "epo_Latn", "name": "Esperanto (Latin)"},
    {"code": "lat_Latn", "name": "Latin"},
    {"code": "hye_Armn", "name": "Armenian"},
    {"code": "kat_Geor", "name": "Georgian"},
    {"code": "azj_Latn", "name": "Azerbaijani (Latin)"},
    {"code": "bel_Cyrl", "name": "Belarusian (Cyrillic)"},
    {"code": "hrv_Latn", "name": "Croatian (Latin)"},
    {"code": "srp_Cyrl", "name": "Serbian (Cyrillic)"},
    {"code": "slv_Latn", "name": "Slovenian (Latin)"},
    {"code": "est_Latn", "name": "Estonian (Latin)"},
    {"code": "lav_Latn", "name": "Latvian (Latin)"},
    {"code": "lit_Latn", "name": "Lithuanian (Latin)"},
    {"code": "mkd_Cyrl", "name": "Macedonian (Cyrillic)"},
    {"code": "sqi_Latn", "name": "Albanian (Latin)"},
    {"code": "bos_Latn", "name": "Bosnian (Latin)"},
    {"code": "mon_Cyrl", "name": "Mongolian (Cyrillic)"},
    {"code": "mri_Latn", "name": "Maori (Latin)"},
    {"code": "haw_Latn", "name": "Hawaiian (Latin)"},
    {"code": "snd_Arab", "name": "Sindhi (Arabic)"},
    {"code": "sin_Sinh", "name": "Sinhala"},
    {"code": "bod_Tibt", "name": "Tibetan"},
    {"code": "dzo_Tibt", "name": "Dzongkha"},
    {"code": "uig_Arab", "name": "Uyghur (Arabic)"},
    {"code": "ckb_Arab", "name": "Kurdish Sorani (Arabic)"},
    {"code": "kmr_Latn", "name": "Kurdish Kurmanji (Latin)"},
    {"code": "ps_Arab", "name": "Pashto (Arabic)"},
    {"code": "ydd_Hebr", "name": "Yiddish (Hebrew)"},
]

# Keep index query mapping quick helper
LANG_MAP = {l["code"]: l["name"] for l in LANGUAGES}

# Maps ISO 639-3 prefixes to ISO 639-1 two-letter Whisper language codes
WHISPER_LANG_MAP = {
    "eng": "en", "hin": "hi", "spa": "es", "fra": "fr", "deu": "de",
    "ita": "it", "jpn": "ja", "zho": "zh", "rus": "ru", "ara": "ar",
    "por": "pt", "urd": "ur", "ben": "bn", "pan": "pa", "mar": "mr",
    "tam": "ta", "tel": "te", "guj": "gu", "kan": "kn", "mal": "ml",
    "kor": "ko", "vie": "vi", "tha": "th", "ind": "id", "tur": "tr",
    "nld": "nl", "pol": "pl", "swe": "sv", "dan": "da", "fin": "fi",
    "ces": "cs", "slk": "sk", "hun": "hu", "ron": "ro", "bul": "bg",
    "ukr": "ua", "ell": "el", "heb": "he"
}

# Maps 2-letter or full name Whisper detected languages back to NLLB-200 code formats
WHISPER_TO_NLLB = {
    "en": "eng_Latn", "english": "eng_Latn",
    "hi": "hin_Deva", "hindi": "hin_Deva",
    "es": "spa_Latn", "spanish": "spa_Latn",
    "fr": "fra_Latn", "french": "fra_Latn",
    "de": "deu_Latn", "german": "deu_Latn",
    "it": "ita_Latn", "italian": "ita_Latn",
    "ja": "jpn_Jpan", "japanese": "jpn_Jpan",
    "zh": "zho_Hans", "chinese": "zho_Hans",
    "ru": "rus_Cyrl", "russian": "rus_Cyrl",
    "ar": "ara_Arab", "arabic": "ara_Arab",
    "ur": "urd_Arab", "urdu": "urd_Arab",
    "bn": "ben_Beng", "bengali": "ben_Beng",
    "pa": "pan_Guru", "punjabi": "pan_Guru",
    "mr": "mar_Deva", "marathi": "mar_Deva",
    "ta": "tam_Taml", "tamil": "tam_Taml",
    "te": "tel_Telu", "telugu": "tel_Telu",
    "gu": "guj_Gujr", "gujarati": "guj_Gujr",
    "kn": "kan_Knda", "kannada": "kan_Knda",
    "ml": "mal_Mlym", "malayalam": "mal_Mlym",
    "ko": "kor_Kore", "korean": "kor_Kore",
    "vi": "vie_Latn", "vietnamese": "vie_Latn",
    "th": "tha_Thai", "thai": "tha_Thai",
    "id": "ind_Latn", "indonesian": "ind_Latn",
    "tr": "tur_Latn", "turkish": "tur_Latn",
    "nl": "nld_Latn", "dutch": "nld_Latn",
    "pl": "pol_Latn", "polish": "pol_Latn",
    "sv": "swe_Latn", "swedish": "swe_Latn",
    "da": "dan_Latn", "danish": "dan_Latn",
    "fi": "fin_Latn", "finnish": "fin_Latn",
    "cs": "ces_Latn", "czech": "ces_Latn",
    "sk": "slk_Latn", "slovak": "slk_Latn",
    "hu": "hun_Latn", "hungarian": "hun_Latn",
    "ro": "ron_Latn", "romanian": "ron_Latn",
    "bg": "bul_Cyrl", "bulgarian": "bul_Cyrl",
    "ua": "ukr_Cyrl", "ukrainian": "ukr_Cyrl",
    "el": "ell_Grek", "greek": "ell_Grek",
    "he": "heb_Hebr", "hebrew": "heb_Hebr"
}
